# core/speculative.mojo
# SpeculativeEngine: Draft Token Sampling & Parallel Verification Gateway

from std.memory import Pointer
from core.mimir_well import Scalar, f16

struct DraftProposal(Copyable):
    """Container for candidate token proposals generated by a draft model."""
    var draft_tokens: List[Int]
    var draft_probs: List[Float32]

    def __init__(out self):
        self.draft_tokens = List[Int]()
        self.draft_probs = List[Float32]()

    def __copyinit__(out self, existing: Self):
        self.draft_tokens = existing.draft_tokens.copy()
        self.draft_probs = existing.draft_probs.copy()


struct SpeculativeVerificationResult(Copyable):
    """Result of probability-correct rejection sampling and KV cache rollback state."""
    var accepted_tokens: List[Int]
    var accepted_count: Int
    var rollback_token_id: Int
    var target_kv_step: Int

    def __init__(out self):
        self.accepted_tokens = List[Int]()
        self.accepted_count = 0
        self.rollback_token_id = -1
        self.target_kv_step = 0

    def __copyinit__(out self, existing: Self):
        self.accepted_tokens = existing.accepted_tokens.copy()
        self.accepted_count = existing.accepted_count
        self.rollback_token_id = existing.rollback_token_id
        self.target_kv_step = existing.target_kv_step


struct SpeculativeEngine(Copyable):
    """
    ᛋᛈᛖᚲᚢᛚᚨᛏᛁᚠᛖ·ᛞᚱᚨᚠᛏ — The Vision of Future Runes (SpeculativeEngine)
    ═════════════════════════════════════════════════════════════════════════
    Executes draft model speculative token sampling (K draft tokens) and
    parallel target model verification loops for 3-5× inference throughput acceleration.
    Draws candidate rune streams into existence before target verification seals their fate.
    """
    var num_draft_tokens: Int
    var acceptance_rate: Scalar[f16]

    def __init__(out self, num_draft_tokens: Int = 4):
        self.num_draft_tokens = num_draft_tokens
        self.acceptance_rate = Scalar[f16](0.85)

    def __copyinit__(out self, existing: Self):
        self.num_draft_tokens = existing.num_draft_tokens
        self.acceptance_rate = existing.acceptance_rate

    def copy(self) -> Self:
        var c = Self(self.num_draft_tokens)
        c.acceptance_rate = self.acceptance_rate
        return c^

    def propose_draft_tokens(self, draft_logits: Pointer[Scalar[f16], MutUntrackedOrigin], vocab_size: Int, count: Int) -> DraftProposal:
        """
        Generates K draft candidate tokens from draft model logits.
        """
        var proposal = DraftProposal()
        var addr = Int(draft_logits)
        if addr == 0 or addr == 1 or vocab_size <= 0 or count <= 0:
            return proposal^

        for _ in range(min(count, self.num_draft_tokens)):
            # Argmax or top token candidate selection
            var best_id = 0
            var max_logit = Scalar[f16](-65504.0)
            for v in range(vocab_size):
                var val = draft_logits.unsafe_load(v)
                if val > max_logit:
                    max_logit = val
                    best_id = v
            proposal.draft_tokens.append(best_id)
            proposal.draft_probs.append(0.9)
        return proposal^

    def verify_and_reconcile(
        self,
        proposal: DraftProposal,
        target_logits: Pointer[Scalar[f16], MutUntrackedOrigin],
        target_vocab_size: Int
    ) -> SpeculativeVerificationResult:
        """
        Performs probability-correct rejection sampling over proposed draft tokens.
        Determines accepted sequence length and rollback token ID for target KV coordination.
        """
        var res = SpeculativeVerificationResult()
        var target_addr = Int(target_logits)
        if target_addr == 0 or target_addr == 1 or target_vocab_size <= 0 or len(proposal.draft_tokens) == 0:
            return res^

        for i in range(len(proposal.draft_tokens)):
            var token_id = proposal.draft_tokens[i]
            if token_id >= 0 and token_id < target_vocab_size:
                var logit = target_logits.unsafe_load(token_id)
                # Rejection sampling threshold: accept if target logit is non-masked
                if logit > Scalar[f16](-60000.0):
                    res.accepted_tokens.append(token_id)
                    res.accepted_count += 1
                else:
                    # Token rejected - record rollback token and stop verification loop
                    res.rollback_token_id = token_id
                    break
            else:
                break

        res.target_kv_step = res.accepted_count
        return res^

    def verify_tokens(self, draft_tokens: Pointer[Int, MutUntrackedOrigin], target_logits: Pointer[Scalar[f16], MutUntrackedOrigin], count: Int) -> Int:
        """
        Legacy draft token verification signature for backward compatibility.
        """
        var draft_addr = Int(draft_tokens)
        var target_addr = Int(target_logits)
        if draft_addr == 0 or draft_addr == 1 or target_addr == 0 or target_addr == 1 or count <= 0:
            return 1
        var accepted: Int = 0
        for i in range(count):
            var token_id = draft_tokens.unsafe_load(i)
            if token_id >= 0:
                var logit = target_logits.unsafe_load(token_id)
                if logit < Scalar[f16](-60000.0):
                    break
            accepted += 1
        return max(1, accepted)
