"""Generate Llama pre-tokenizer character classes from Unicode 16.0 data.

Build tooling only; the resulting sorted range table is native Mojo data.
Source: https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt
Unicode data license: https://www.unicode.org/license.txt
"""
import argparse
import hashlib
from pathlib import Path


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("input", type=Path)
    p.add_argument("output", type=Path)
    args = p.parse_args()
    raw = args.input.read_bytes()
    ranges = []
    first = None
    for line in raw.decode("utf-8").splitlines():
        fields = line.split(";")
        code = int(fields[0], 16)
        category = 1 if fields[2].startswith("L") else 2 if fields[2].startswith("N") else 0
        if fields[1].endswith(", First>"):
            first = code
            continue
        start = first if fields[1].endswith(", Last>") else code
        first = None
        if category:
            if ranges and ranges[-1][1] + 1 == start and ranges[-1][2] == category:
                ranges[-1] = (ranges[-1][0], code, category)
            else:
                ranges.append((start, code, category))
    width = 1 << (len(ranges) - 1).bit_length()
    vectors = []
    for column, name in enumerate(("STARTS", "ENDS", "CLASSES")):
        data = [str(row[column]) for row in ranges] + ["0"] * (width - len(ranges))
        vectors.append(f"comptime {name} = SIMD[DType.int32, {width}](" + ", ".join(data) + ")")
    entries = "\n".join(vectors)
    source = '''"""Unicode 16.0 L/N ranges. Generated by scripts/generate_unicode_categories.py.

UnicodeData.txt SHA-256: DIGEST
Unicode License v3; see THIRD_PARTY_NOTICES.md. Runtime is native Mojo.
"""
ENTRIES


def llama_character_class(code: Int) -> Int:
    """Return 1=letter, 2=number, 3=regex whitespace, or 0=other."""
    if code == 32 or 9 <= code <= 13 or code == 133 or code == 160 or code == 5760 or 8192 <= code <= 8202 or code == 8232 or code == 8233 or code == 8239 or code == 8287 or code == 12288:
        return 3
    var low = 0
    var high = RANGE_COUNT
    while low < high:
        var middle = (low + high) // 2
        if code < Int(STARTS[middle]):
            high = middle
        elif code > Int(ENDS[middle]):
            low = middle + 1
        else:
            return Int(CLASSES[middle])
    return 0
'''.replace("DIGEST", hashlib.sha256(raw).hexdigest()).replace("ENTRIES", entries).replace("RANGE_COUNT", str(len(ranges)))
    args.output.write_text(source, encoding="utf-8", newline="\n")
    print(f"Generated {len(ranges)} Unicode letter/number ranges")


if __name__ == "__main__":
    main()
