#!/usr/bin/env python3
"""Generate Mojo IQ lookup tables from llama.cpp's gguf-py quants.py."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path


EXPECTED_COUNTS = {"IQ2_XXS": 256, "IQ1_S": 2048}


def extract_tables(source: Path) -> dict[str, list[int]]:
    tree = ast.parse(source.read_text(encoding="utf-8"), filename=str(source))
    tables: dict[str, list[int]] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef) or node.name not in EXPECTED_COUNTS:
            continue
        for item in node.body:
            if not isinstance(item, ast.Assign):
                continue
            if not any(isinstance(target, ast.Name) and target.id == "grid_hex" for target in item.targets):
                continue
            encoded = ast.literal_eval(item.value)
            if not isinstance(encoded, bytes):
                raise ValueError(f"{node.name}.grid_hex is not a bytes literal")
            raw = bytes.fromhex(encoded.decode("ascii"))
            if len(raw) % 2 != 0:
                raise ValueError(f"{node.name}.grid_hex has an odd decoded length")
            tables[node.name] = [
                int.from_bytes(raw[offset : offset + 2], "little")
                for offset in range(0, len(raw), 2)
            ]
    for name, expected in EXPECTED_COUNTS.items():
        actual = len(tables.get(name, []))
        if actual != expected:
            raise ValueError(f"{name} grid count is {actual}, expected {expected}")
    return tables


def render(tables: dict[str, list[int]]) -> str:
    lines = [
        '"""Generated GGML IQ codebook indices.',
        "",
        "Generated by scripts/generate_iq_codebooks.py from llama.cpp gguf-py.",
        "Each UInt16 packs eight 2-bit grid digits, least-significant digit first.",
        '"""',
        "",
    ]
    for name in ("IQ2_XXS", "IQ1_S"):
        values = tables[name]
        lines.append(f"comptime {name}_GRID = SIMD[DType.uint16, {len(values)}](")
        for offset in range(0, len(values), 12):
            row = ", ".join(f"0x{value:04X}" for value in values[offset : offset + 12])
            lines.append(f"    {row},")
        lines.extend((")", ""))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="path to llama.cpp gguf-py/gguf/quants.py")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("aesir_engine/core/iq_codebooks.mojo"),
    )
    args = parser.parse_args()
    args.output.write_text(render(extract_tables(args.source)), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
